### PR TITLE
indexable graphic attributes

### PR DESCRIPTION
**Pull request by kushalkolar**
implements #77

GraphicFeatures to implement:

- [x] colors
- [ ] sizes
- [x] data - mostly wrap current `update_data` methods, just pass the slice obj directly to geo.grid or geo.positions, and for positions update_range with indices parsed by slice object, otherwise entire thing with grid.
- [x] present (different from visibility) - not indexable 
- [x] events for when these change

### CODE REVIEW

**Comment by kushalkolar** [comment]
color indexing is really nice :D 

https://user-images.githubusercontent.com/9403332/208393879-0d373a23-9596-46f6-b07b-3a9facd6e95d.mp4

**Comment by kushalkolar** [comment]
this insanity is possible now: https://www.youtube.com/watch?v=j_gwi-Wf1Ao

also this which is more useful :smile: 

image

**Comment by kushalkolar** [comment]
For scatter we can make size an indexable feature too.

**Comment by kushalkolar** [comment]
@EricThomson, @clewis7 , @ArjunPutcha
guys this is pretty epic, changing a `GraphicFeature` can trigger events :smile: 

Caitlin, `pick_info` formatting is the same as pygfx events to make life easy :D 

https://user-images.githubusercontent.com/9403332/209122940-961f3157-5e81-4912-9953-e4c95221d2b8.mp4

**Comment by EricThomson** [comment]
Nice -- this will make certain other things so much easier.

**Pull request merged**
