### PR TITLE
storing graphics in dict

### PR DESCRIPTION
**Pull request by clewis7**
addresses #64

moved to store graphics in dict with keys as the graphic class

keys currently need to passed in as a string, need to work on implementation to allow for 

```python 
gp[0,0].get_graphics()[ImageGraphic]
```
as opposed to 
```python
gp[0,0].get_graphics()["ImageGraphic"]

### CODE REVIEW

**Comment by clewis7** [comment]
right now, I have it creating the keys to the dict by 
```python 
self._graphics[graphic.__class__.__name__] = list()
self._graphics[graphic.__class__.__name__].append(graphic)
```
but ```__name__``` returns a string, any suggestions on how to get graphic class name not as a string when just ```__class__``` gives ```fastplotlib.graphics.image.ImageGraphic```

**Comment by kushalkolar** [comment]
yea not sure whether the best approach is to have it as a `str` or the class type itself, I think using `graphic.__class__` should work, you can check if: 

```python3
graphic.__class__ is ImageGraphic
```

**Comment by kushalkolar** [comment]
after this is done modify the `__repr__` for `PlotArea` such that if there are > 5 graphics of any type, show only the first 5 and last 5 because I know there will be _someone_ at the workshop who crashes their jupyter because they ended up calling the repr while having 10,000 graphics in a gridplot :upside_down_face:

**Comment by kushalkolar** [comment]
Now that #78 brings events to `GraphicFeatures` we want to make `link()` work seamlessly for both `pygfx` events and `GraphicFeature` events. Something like this should work:

```python
def link(self, event_type: str, target: Any, ...):
  pygfx_events = ["click", ...]
  graphic_feature_events = ["colors", "data", "present", ...]

  if event_type in pygfx_events:
    self.world_object.add_event_handler(...)

  elif event_type in graphic_feature_events:
    feature = getattr(self, event_type)
    feature.add_event_handler(...)
```

**Comment by kushalkolar** [comment]
after #88 there is now a class attribute that stores the name of the graphic as a str in lower case, see: https://github.com/kushalkolar/fastplotlib/pull/88/files#diff-a57994ecff1cde4e05c8175265219f0b5200da144ce8733b9eb560c09bcea7ddR9

**Comment by kushalkolar** [comment]
rebase on mater or just start a new PR, this is pretty straight forward.

**Comment by kushalkolar** [comment]
I think that since `PlotAreas` are indexable we don't really need this. We can revisit if it becomes necessary in the future.

**Pull request closed without merging**
